In [1]:
import sys
import pandas as pd

print("Python:", sys.executable)
print("Pandas:", pd.__version__)

Python: d:\Gói 1\Stock_Analytics_Project\.venv\Scripts\python.exe
Pandas: 3.0.5

In [2]:
import pandas as pd
from pathlib import Path

In [3]:
BASE_DIR = Path(".")

print("Thư mục project:", BASE_DIR.resolve())

Thư mục project: D:\Gói 1\Stock_Analytics_Project

In [4]:
FILES = {
    "HNX": BASE_DIR / "CafeF.HNX.Upto03.09.2026.csv",
    "UPCOM": BASE_DIR / "CafeF.UPCOM.Upto03.09.2026.csv",
    "HOSE": BASE_DIR / "CafeF.HSX.Upto03.09.2026.csv"
}

FILES

{'HNX': WindowsPath('CafeF.HNX.Upto03.09.2026.csv'),
 'UPCOM': WindowsPath('CafeF.UPCOM.Upto03.09.2026.csv'),
 'HOSE': WindowsPath('CafeF.HSX.Upto03.09.2026.csv')}

In [5]:
def load_one_file(file_path, exchange):
   
    # ---------------------------------------------------------
    # 1. Kiểm tra file có tồn tại hay không
    # ---------------------------------------------------------
    if not file_path.exists():
        raise FileNotFoundError(
            f"Không tìm thấy file: {file_path}"
        )

    # ---------------------------------------------------------
    # 2. Một số file CSV có thể sử dụng encoding khác nhau.
    #    Vì vậy, ta thử lần lượt một số encoding phổ biến.
    # ---------------------------------------------------------
    encodings = [
        "utf-8-sig",
        "utf-8",
        "cp1252"
    ]

    df = None
    last_error = None

    for encoding in encodings:
        try:
            df = pd.read_csv(
                file_path,
                encoding=encoding
            )

            print(
                f"Đọc thành công: {file_path.name} "
                f"| encoding = {encoding}"
            )

            break

        except UnicodeDecodeError as e:
            last_error = e

    # ---------------------------------------------------------
    # 3. Nếu tất cả encoding đều thất bại
    # ---------------------------------------------------------
    if df is None:
        raise UnicodeDecodeError(
            "Không thể đọc file bằng các encoding đã thử."
        ) from last_error

    # ---------------------------------------------------------
    # 4. Loại bỏ khoảng trắng thừa ở tên cột.
    #
    #    Ví dụ:
    #    " <Ticker> " → "<Ticker>"
    # ---------------------------------------------------------
    df.columns = (
        df.columns
        .astype(str)
        .str.strip()
    )

    # ---------------------------------------------------------
    # 5. Thêm cột exchange dựa trên nguồn file.
    #
    #    HNX file   → HNX
    #    UPCOM file → UPCOM
    #    HSX file   → HOSE
    # ---------------------------------------------------------
    df["exchange"] = exchange

    # ---------------------------------------------------------
    # 6. In thông tin cơ bản để kiểm tra dữ liệu.
    # ---------------------------------------------------------
    print(f"Số dòng: {len(df):,}")
    print(f"Số cột: {len(df.columns)}")

    return df

In [6]:
df_hnx = load_one_file(
    FILES["HNX"],
    "HNX"
)

df_hnx.head()

Đọc thành công: CafeF.HNX.Upto03.09.2026.csv | encoding = utf-8-sig
Số dòng: 919,101
Số cột: 8

  <Ticker>  <DTYYYYMMDD>  <Open>  <High>  <Low>  <Close>  <Volume> exchange
0      AMC      20260903    13.6    13.6   13.6     13.6       200      HNX
1      AME      20260903     6.8     6.8    6.8      6.8      2700      HNX
2      AMV      20260903     1.2     1.2    1.1      1.2     76300      HNX
3      API      20260903     5.5     5.7    5.5      5.6     55600      HNX
4      APS      20260903     6.1     6.2    6.0      6.2    144100      HNX

In [7]:
df_hnx.columns.tolist()

['<Ticker>',
 '<DTYYYYMMDD>',
 '<Open>',
 '<High>',
 '<Low>',
 '<Close>',
 '<Volume>',
 'exchange']

In [8]:
df_hnx["exchange"].value_counts()

exchange
HNX    919101
Name: count, dtype: int64

In [9]:
df_hnx.head()

  <Ticker>  <DTYYYYMMDD>  <Open>  <High>  <Low>  <Close>  <Volume> exchange
0      AMC      20260903    13.6    13.6   13.6     13.6       200      HNX
1      AME      20260903     6.8     6.8    6.8      6.8      2700      HNX
2      AMV      20260903     1.2     1.2    1.1      1.2     76300      HNX
3      API      20260903     5.5     5.7    5.5      5.6     55600      HNX
4      APS      20260903     6.1     6.2    6.0      6.2    144100      HNX

In [10]:
df_upcom = load_one_file(
    FILES["UPCOM"],
    "UPCOM"
)

df_upcom.head()

Đọc thành công: CafeF.UPCOM.Upto03.09.2026.csv | encoding = utf-8-sig
Số dòng: 868,542
Số cột: 8

  <Ticker>  <DTYYYYMMDD>  <Open>  <High>  <Low>  <Close>  <Volume> exchange
0      AAH      20260903     1.9     1.9    1.8      1.9    103400    UPCOM
1      AAS      20260903     7.7     8.2    7.6      8.1   2449900    UPCOM
2      AAV      20260903     6.0     6.1    5.9      5.9    250900    UPCOM
3      ABB      20260903    17.3    17.3   17.2     17.2    319400    UPCOM
4      ABC      20260903    10.0    10.1   10.0     10.1       900    UPCOM

In [11]:
df_hose = load_one_file(
    FILES["HOSE"],
    "HOSE"
)

df_hose.head()

Đọc thành công: CafeF.HSX.Upto03.09.2026.csv | encoding = utf-8-sig
Số dòng: 1,535,947
Số cột: 8

  <Ticker>  <DTYYYYMMDD>  <Open>  <High>  <Low>  <Close>  <Volume> exchange
0      AAA      20260903    7.08    7.16   7.03     7.09    659500     HOSE
1      AAM      20260903    7.49    7.74   7.49     7.60      7900     HOSE
2      AAN      20260903   16.00   16.10  15.85    16.10    277900     HOSE
3      AAT      20260903    2.29    2.29   2.23     2.24     28400     HOSE
4      ABR      20260903   11.20   11.30  11.20    11.30       400     HOSE

In [12]:
raw_df = pd.concat(
    [
        df_hnx,
        df_upcom,
        df_hose
    ],
    ignore_index=True
)

print("Kích thước Raw DataFrame:", raw_df.shape)

Kích thước Raw DataFrame: (3323590, 8)

In [13]:
raw_df["exchange"].value_counts()

exchange
HOSE     1535947
HNX       919101
UPCOM     868542
Name: count, dtype: int64

In [14]:
raw_df.head()

  <Ticker>  <DTYYYYMMDD>  <Open>  <High>  <Low>  <Close>  <Volume> exchange
0      AMC      20260903    13.6    13.6   13.6     13.6       200      HNX
1      AME      20260903     6.8     6.8    6.8      6.8      2700      HNX
2      AMV      20260903     1.2     1.2    1.1      1.2     76300      HNX
3      API      20260903     5.5     5.7    5.5      5.6     55600      HNX
4      APS      20260903     6.1     6.2    6.0      6.2    144100      HNX

In [15]:
print("Số dòng:", len(raw_df))
print("Số cột:", len(raw_df.columns))

print("\nCác sàn:")
print(raw_df["exchange"].unique())

print("\nTên các cột:")
print(raw_df.columns.tolist())

Số dòng: 3323590
Số cột: 8

Các sàn:
<StringArray>
['HNX', 'UPCOM', 'HOSE']
Length: 3, dtype: str

Tên các cột:
['<Ticker>', '<DTYYYYMMDD>', '<Open>', '<High>', '<Low>', '<Close>', '<Volume>', 'exchange']

In [16]:
def apply_schema(df):
    """
    Chuẩn hóa Raw DataFrame từ cấu trúc CafeF
    về schema thống nhất của project.

    Schema đầu ra:
    ticker
    exchange
    date
    open
    high
    low
    close
    volume
    """

    # ---------------------------------------------------------
    # 1. Khai báo mapping giữa tên cột gốc của CafeF
    #    và tên cột chuẩn của project
    # ---------------------------------------------------------
    column_mapping = {
        "<Ticker>": "ticker",
        "<DTYYYYMMDD>": "date",
        "<Open>": "open",
        "<High>": "high",
        "<Low>": "low",
        "<Close>": "close",
        "<Volume>": "volume",
        "exchange": "exchange"
    }

    # ---------------------------------------------------------
    # 2. Kiểm tra xem Raw DataFrame có đủ các cột cần thiết
    #    hay không
    # ---------------------------------------------------------
    required_columns = list(column_mapping.keys())

    missing_columns = [
        col for col in required_columns
        if col not in df.columns
    ]

    if missing_columns:
        raise ValueError(
            f"Thiếu các cột cần thiết: {missing_columns}"
        )

    # ---------------------------------------------------------
    # 3. Chỉ lấy những cột cần thiết cho project
    # ---------------------------------------------------------
    df = df[required_columns].copy()

    # ---------------------------------------------------------
    # 4. Đổi tên cột theo schema chuẩn
    # ---------------------------------------------------------
    df = df.rename(columns=column_mapping)

    # ---------------------------------------------------------
    # 5. Chuẩn hóa ticker và exchange thành kiểu string
    # ---------------------------------------------------------
    df["ticker"] = df["ticker"].astype("string")
    df["exchange"] = df["exchange"].astype("string")

    # ---------------------------------------------------------
    # 6. Chuyển date từ dạng YYYYMMDD
    #    Ví dụ:
    #    20260903 → 2026-09-03
    #
    #    errors="coerce" giúp giá trị ngày không hợp lệ
    #    chuyển thành NaT thay vì làm chương trình bị dừng.
    # ---------------------------------------------------------
    df["date"] = pd.to_datetime(
        df["date"],
        format="%Y%m%d",
        errors="coerce"
    )

    # ---------------------------------------------------------
    # 7. Chuyển các biến giá sang kiểu số
    # ---------------------------------------------------------
    price_columns = [
        "open",
        "high",
        "low",
        "close"
    ]

    for col in price_columns:
        df[col] = pd.to_numeric(
            df[col],
            errors="coerce"
        ).astype("float64")

    # ---------------------------------------------------------
    # 8. Chuyển volume sang kiểu số
    #
    #    Dùng Int64 dạng nullable của Pandas để vẫn có thể
    #    chứa giá trị thiếu (NA) nếu xuất hiện.
    # ---------------------------------------------------------
    df["volume"] = pd.to_numeric(
        df["volume"],
        errors="coerce"
    ).astype("Int64")

    # ---------------------------------------------------------
    # 9. Sắp xếp đúng thứ tự schema của project
    # ---------------------------------------------------------
    schema = [
        "ticker",
        "exchange",
        "date",
        "open",
        "high",
        "low",
        "close",
        "volume"
    ]

    df = df[schema]

    return df

In [17]:
standardized_df = apply_schema(raw_df)

print("Kích thước dữ liệu:", standardized_df.shape)

Kích thước dữ liệu: (3323590, 8)

In [18]:
standardized_df.head()

  ticker exchange       date  open  high   low  close  volume
0    AMC      HNX 2026-09-03  13.6  13.6  13.6   13.6     200
1    AME      HNX 2026-09-03   6.8   6.8   6.8    6.8    2700
2    AMV      HNX 2026-09-03   1.2   1.2   1.1    1.2   76300
3    API      HNX 2026-09-03   5.5   5.7   5.5    5.6   55600
4    APS      HNX 2026-09-03   6.1   6.2   6.0    6.2  144100

In [19]:
standardized_df.dtypes

ticker              string
exchange            string
date        datetime64[us]
open               float64
high               float64
low                float64
close              float64
volume               Int64
dtype: object

In [20]:
standardized_df.columns.tolist()

['ticker', 'exchange', 'date', 'open', 'high', 'low', 'close', 'volume']

In [21]:
standardized_df["exchange"].value_counts()

exchange
HOSE     1535947
HNX       919101
UPCOM     868542
Name: count, dtype: Int64

In [22]:
def get_raw_data(base_dir=BASE_DIR):
    """
    Thực hiện toàn bộ quy trình Data Acquisition:

    1. Đọc 3 file CSV local của CafeF
    2. Gán exchange cho từng file
    3. Gộp dữ liệu thành một DataFrame
    4. Chuẩn hóa schema
    5. Trả về DataFrame hoàn chỉnh
    """

    # ---------------------------------------------------------
    # Bước 1: Đọc dữ liệu từ 3 file CSV
    # ---------------------------------------------------------
    raw_df = load_local_data(base_dir)

    # ---------------------------------------------------------
    # Bước 2: Chuẩn hóa schema
    # ---------------------------------------------------------
    standardized_df = apply_schema(raw_df)

    # ---------------------------------------------------------
    # Bước 3: Trả về DataFrame
    # ---------------------------------------------------------
    return standardized_df

In [23]:
def load_local_data(base_dir=BASE_DIR):
    """
    Đọc đúng 3 file CSV local của CafeF,
    gán exchange và gộp thành một Raw DataFrame.
    """

    dataframes = []

    # ---------------------------------------------------------
    # Duyệt qua 3 file HNX, UPCOM và HOSE
    # ---------------------------------------------------------
    for exchange, filename in [
        ("HNX", "CafeF.HNX.Upto03.09.2026.csv"),
        ("UPCOM", "CafeF.UPCOM.Upto03.09.2026.csv"),
        ("HOSE", "CafeF.HSX.Upto03.09.2026.csv")
    ]:

        # Tạo đường dẫn đầy đủ tới file
        file_path = base_dir / filename

        # Đọc file và thêm exchange
        df = load_one_file(
            file_path,
            exchange
        )

        # Lưu DataFrame vào danh sách
        dataframes.append(df)

    # ---------------------------------------------------------
    # Gộp 3 DataFrame thành một DataFrame duy nhất
    # ---------------------------------------------------------
    raw_df = pd.concat(
        dataframes,
        ignore_index=True,
        sort=False
    )

    return raw_df

In [24]:
standardized_df = get_raw_data()

print("Data Acquisition hoàn tất!")
print("Kích thước dữ liệu:", standardized_df.shape)

Đọc thành công: CafeF.HNX.Upto03.09.2026.csv | encoding = utf-8-sig
Số dòng: 919,101
Số cột: 8
Đọc thành công: CafeF.UPCOM.Upto03.09.2026.csv | encoding = utf-8-sig
Số dòng: 868,542
Số cột: 8
Đọc thành công: CafeF.HSX.Upto03.09.2026.csv | encoding = utf-8-sig
Số dòng: 1,535,947
Số cột: 8
Data Acquisition hoàn tất!
Kích thước dữ liệu: (3323590, 8)

In [25]:
print("Columns:")
print(standardized_df.columns.tolist())

print("\nDtypes:")
print(standardized_df.dtypes)

Columns:
['ticker', 'exchange', 'date', 'open', 'high', 'low', 'close', 'volume']

Dtypes:
ticker              string
exchange            string
date        datetime64[us]
open               float64
high               float64
low                float64
close              float64
volume               Int64
dtype: object

In [26]:
print(standardized_df["exchange"].value_counts())

exchange
HOSE     1535947
HNX       919101
UPCOM     868542
Name: count, dtype: Int64

In [27]:
standardized_df.head()

  ticker exchange       date  open  high   low  close  volume
0    AMC      HNX 2026-09-03  13.6  13.6  13.6   13.6     200
1    AME      HNX 2026-09-03   6.8   6.8   6.8    6.8    2700
2    AMV      HNX 2026-09-03   1.2   1.2   1.1    1.2   76300
3    API      HNX 2026-09-03   5.5   5.7   5.5    5.6   55600
4    APS      HNX 2026-09-03   6.1   6.2   6.0    6.2  144100

In [28]:
standardized_df.tail()

        ticker exchange       date    open    high     low   close  volume
3323585    SAM     HOSE 2000-08-02  1.9775  1.9775  1.9775  1.9777     200
3323586    REE     HOSE 2000-07-31  0.7417  0.7417  0.7417  0.7420     300
3323587    SAM     HOSE 2000-07-31  1.9436  1.9436  1.9436  1.9438   10000
3323588    REE     HOSE 2000-07-28  0.7280  0.7280  0.7280  0.7283    1000
3323589    SAM     HOSE 2000-07-28  1.9210  1.9210  1.9210  1.9212    3200

In [29]:
rows, columns = standardized_df.shape

print(f"Số dòng: {rows:,}")
print(f"Số cột: {columns}")

Số dòng: 3,323,590
Số cột: 8

In [30]:
standardized_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3323590 entries, 0 to 3323589
Data columns (total 8 columns):
 #   Column    Dtype
---  ------    -----
 0   ticker    string
 1   exchange  string
 2   date      datetime64[us]
 3   open      float64
 4   high      float64
 5   low       float64
 6   close     float64
 7   volume    Int64
dtypes: Int64(1), datetime64[us](1), float64(4), string(2)
memory usage: 206.0 MB

In [31]:
output_path = BASE_DIR / "raw_data.csv"

standardized_df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig",
    date_format="%Y-%m-%d"
)

print(f"Đã lưu dữ liệu tại: {output_path.resolve()}")

Đã lưu dữ liệu tại: D:\Gói 1\Stock_Analytics_Project\raw_data.csv